### ISSUE TITLE
Hover effect on sidebar is bugged (see below)

### ISSUE THREAD

**Issue by zeusssz** [pranavinsight/matrixtype-og#1]
![image](https://github.com/pranavinsight/matrixtype-og/assets/136583387/2e6b85f6-0116-48bc-9ef8-d8c70780fe3e)
the above hover effect is bugged. when putting mouse pointer on a button, the effect positions itself onto the next button, simultaneously making the text on both buttons invisible, due to the hover definitions in the css

**Comment by pranavinsight** [comment]
Oh, yeah... bugs can sometimes happen... You can try restarting the webpage or feel free to discuss the problem with me if it does not work.
.

**Comment by pranavinsight** [comment]
Thank you  Mister @zeusssz for informing me :) Keep sharing some feedback, that will make me happy. Feel free to discuss some bug fixes, i will surely fix that in the future. Thank  you @zeusssz ! See ya
